apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend-deployment
  labels:
    app: store-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
      - name: store-frontend
        image: chaphe/frontend-store-image:1.0
        ports:
        - containerPort: 80
        env:
        - name: REVIEWS_URL
          value: http://192.168.0.105:30200
        - name: STORE_URL
          value: http://192.168.0.105:30400
        - name: CATALOG_URL
          value: http://192.168.0.105:30300 
---
apiVersion: v1
kind: Service
metadata:
  name: store-frontend-service
spec:
  type: NodePort
  selector:
    app: store-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30401