version: '3.9'
services:
  aplication:
    container_name: exampleapp
    build: .
    ports:
      - "5000:4000"
    links:
      - redis
    volumes:
      - .:/usr/src/app
  redis: 
    container_name: redisapp
    image: redis
    ports:
      - "27017:27017"